units:
  kx: cx
  ky: cy
  px: kx + 2
  py: ky + 2
points:
  key:
    padding: cy
  zones:
    matrix:
      anchor:
        rotate: 20
        shift: [110, -100]
      columns:
        macro:
        pinky:
        ring:
          key.splay: 0
          key.origin: [-12, -19]
          key.stagger: 5
        middle:
          key.stagger: 5
        index:
          key.stagger: -7
        inner:
          key.stagger: -3
      rows:
        bottom:
        middle:
        top:
        num:
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [-7, -19]
      columns:
        home:
          key.splay: -30
          key.origin: [-5.75, -20]
        far:
          key.spread: 21.25
          key.splay: 0
          key.stagger: 4
      rows:
        thumb:
  rotate: -20
outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5,ky-0.5]

  board:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_macro_num
          shift: [-0.5px,0.5py+11]
        - ref: matrix_macro_bottom
          shift: [-0.5px,-0.5py]
        - ref: matrix_ring_bottom
          shift: [-7,-0.5py-5]
        - ref: matrix_ring_bottom
          shift: [-7,-0.5py]
        - ref: matrix_ring_bottom
          shift: [px,-0.5py]
        - ref: matrix_index_bottom
          shift: [4,-py]
        - ref: thumbfan_home_thumb
          shift: [-0.5px+1,-0.5py-1]
        - ref: thumbfan_home_thumb
          shift: [0.5px+3,-0.5py-1]
        - ref: thumbfan_far_thumb
          shift: [0.5px,-0.5py-5]
        - ref: thumbfan_far_thumb
          shift: [0.5px,0.5py]
        - ref: matrix_inner_bottom
          shift: [0.5px+7,-0.5py-8]
        - ref: matrix_inner_bottom
          shift: [0.5px+7,-0.5py]
        - ref: matrix_inner_bottom
          shift: [0.5px,0]
        - ref: matrix_inner_num
          shift: [0.5px,0.5py]
        - ref: matrix_inner_num
          shift: [-0.5px+1,0.5py]
        - ref: matrix_inner_num
          shift: [-0.5px+1,0.5py+4]
        - ref: matrix_index_num
          shift: [-0.5px+1,0.5py+1]
        - ref: matrix_middle_num
          shift: [0.5px,0.5py+1]
  combo:
    - name: board
    - operation: subtract
      name: keys
pcbs:
  main_pcb:
    outlines:
      main:
        outline: board
    footprints:
      choc_hotswap:
        what: choc
        params:
          from: =column_net
          to: GND
          keycaps: true
          reverse: true
          hotswap: true
      choc:
        what: choc
        params:
          from: =column_net
          to: GND
          keycaps: true
          reverse: true
