units:
  kx: cx
  ky: cy
  px: kx + 2
  py: ky + 2
points:
  key:
    padding: cy
  zones:
    matrix:
      anchor:
        rotate: 0
        shift: [75, -75]
      columns:
        macro:
          key:
            column_net: 
        pinky:
        ring:
          key.splay: 0
          key.origin: [-12, -19]
          key.stagger: 5
        middle:
          key.stagger: 5
        index:
          key.stagger: -7
        inner:
          key.stagger: -3
      rows:
        bottom:
          row_net: P010
        middle:
          row_net: P011
        top:
          row_net: P106
        num:
          row_net: P104
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [-7, -19]
      columns:
        home:
          key.splay: -30
          key.origin: [-5.75, -20]
        far:
          key.spread: 21.25
          key.splay: 0
          key.stagger: 4
      rows:
        thumb:
          row_net: P009
        
  rotate: -20
  # mirror:
  #   ref: thumbfan_far_thumb
  #   distance: 100
outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5,ky-0.5]

  board:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        # Top left
        - ref: matrix_macro_num
          shift: [-0.5px,0.5py+11]
        # Bottom left
        - ref: matrix_macro_bottom
          shift: [-0.5px,-0.5py]
        # Notch under Ring col
        - ref: matrix_ring_bottom
          shift: [-7,-0.5py-5]
        - ref: matrix_ring_bottom
          shift: [-7,-0.5py]
        - ref: matrix_ring_bottom
          shift: [px,-0.5py]
        # Start of diagonal under Index col
        - ref: matrix_index_bottom
          shift: [4,-py]
        # Around thumbfan
        - ref: thumbfan_home_thumb
          shift: [-0.5px+1,-0.5py-1]
        - ref: thumbfan_home_thumb
          shift: [0.5px+3,-0.5py-1]
        - ref: thumbfan_far_thumb
          shift: [0.5px,-0.5py-5]
        - ref: thumbfan_far_thumb
          shift: [0.5px,0.5py]
        - ref: matrix_inner_bottom
          shift: [0.5px+7,-0.5py-8]
        - ref: matrix_inner_bottom
          shift: [0.5px+7,-0.5py]
        - ref: matrix_inner_bottom
          shift: [0.5px,0]
        - ref: matrix_inner_num
          shift: [0.5px,0.5py]
        - ref: matrix_inner_num
          shift: [-0.5px+1,0.5py]
        - ref: matrix_inner_num
          shift: [-0.5px+1,0.5py+4]
        - ref: matrix_index_num
          shift: [-0.5px+1,0.5py+1]
        - ref: matrix_middle_num
          shift: [0.5px,0.5py+1]
  combo:
    - name: board
    - operation: subtract
      name: keys
pcbs:
  main_pcb:
    template: kicad8 # Required, since footprints are KiCad 8 only
    outlines:
      main:
        outline: board
    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:
          from: =column_net
          to: GND
          keycaps: true
          reverse: true
          hotswap: true
      diode:
        what: ceoloide/diode_tht_sod123
        where: true
        params:
          reversible: true
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [-5, -3]
      # led:
      #   what: ceoloide/led_sk6812mini-e
      #   where: true
      #   params:
      #     P2:
      #   adjust:
      #     shift: [0, -8]
      nice_nano:
        what: garethbradley/mcu_nice_nano_v2
        params:
          reversible: true
          reverse_mount: true
        where:
          ref: matrix_inner_top
          shift: [px,-8]
          rotate: 0
