units:
  kx: cx
  ky: cy
  px: kx + 2
  py: ky + 2
points:
  key:
    padding: cy
  zones:
    matrix:
      anchor:
        rotate: 0
        shift: [75, -75]
      columns:
        macro:
          key:
            column_net: 
        pinky:
        ring:
          key.splay: 0
          key.origin: [-12, -19]
          key.stagger: 5
        middle:
          key.stagger: 3
        index:
          key.stagger: -3
        inner:
          key.stagger: -3
      rows:
        bottom:
          row_net: P010
        middle:
          row_net: P011
        top:
          row_net: P106
        # num:
        #   row_net: P104
    thumbfan:
      anchor:
        ref: matrix_index_bottom
        shift: [-12, -18.5]
      columns:
        near:
          key.splay: 0
        home:
          key.spread: 21.25
          key.splay: -15
          key.stagger: -3
        far:
          key.spread: 23.25
          key.splay: -20
          key.stagger: -0
      rows:
        thumb:
          row_net: P009
        
  rotate: 0
  # mirror:
  #   ref: thumbfan_far_thumb
  #   distance: 100
outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5,ky-0.5]
    - what: rectangle
      where: thumbfan_far_thumb
      size: [kx-0.5,1.5ky-0.5]

  board:
    - what: polygon
      operation: stack
      fillet: 1.5
      points:
        # Top left
        - ref: matrix_macro_top
          shift: [-0.5px,0.5py+8]
        # Bottom left
        - ref: matrix_macro_bottom
          shift: [-0.5px,-0.5py]
        # Notch under Ring col
        #- ref: matrix_ring_bottom
        #  shift: [-7,-0.5py-5]
        - ref: matrix_ring_bottom
          shift: [-7,-0.5py-5]
        - ref: matrix_ring_bottom
          shift: [0.5px-8,-0.5py-5]
        # Start of diagonal under Index col
        #- ref: matrix_index_bottom
        #  shift: [4,-py]
        # Around thumbfan
        - ref: thumbfan_near_thumb
          shift: [-0.5px-2,-0.5py-1]
        - ref: thumbfan_home_thumb
          shift: [0.5px,-0.5py-1]
        - ref: thumbfan_far_thumb
          shift: [0.5px,-0.5py-5]
        - ref: thumbfan_far_thumb
          shift: [0.5px,0.5py+10]
        # Over top of thumbfan far
        #- ref: thumbfan_far_thumb
        #  shift: [0.5px-2,0.5py+5]
        # Top right above MCU
        - ref: matrix_inner_top
          shift: [1.5px+2,0.5py-4]
        # Step above MCU
        - ref: matrix_inner_top
          shift: [0.5px,0.5py-4.001]
        - ref: matrix_inner_top
          shift: [0.5px,0.5py]
        - ref: matrix_inner_top
          shift: [-0.5px+1,0.5py]
        - ref: matrix_inner_top
          shift: [-0.5px+1,0.5py+3.001]
        - ref: matrix_index_top
          shift: [-0.5px+1,0.5py]
        - ref: matrix_middle_top
          shift: [0.5px,0.5py+0.001]
  combo:
    - name: board
    - operation: subtract
      name: keys
pcbs:
  main_pcb:
    template: kicad8 # Required, since footprints are KiCad 8 only
    outlines:
      main:
        outline: board
    footprints:
      choc_hotswap:
        what: garethbradley/choc
        where: true
        params:
          from: =column_net
          to: GND
          # keycaps: true
          reverse: true
          hotswap: true
      diode:
        what: ceoloide/diode_tht_sod123
        where: true
        params:
          reversible: true
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [-5, -3]
      # led:
      #   what: ceoloide/led_sk6812mini-e
      #   where: true
      #   params:
      #     P2:
      #   adjust:
      #     shift: [0, -8]
      nice_nano:
        what: garethbradley/mcu_nice_nano_v2
        params:
          # reversible: true
          # reverse_mount: true
          mcu_3dmodel_filename: ${EG_INFUSED_KIM_3D_MODELS}/Nice_Nano_V2.step
        where:
          ref: matrix_inner_top
          shift: [px+1,-11.5]
          rotate: 0
      nice_view:
        what: garethbradley/nice_view
        params:
          # reversible: true
          # reverse_mount: true
        where:
          ref: matrix_inner_top
          shift: [px+1,-14.5]
          rotate: 0
      batt_conn:
        what: garethbradley/battery_connector_jst_ph_2
        where:
          ref: matrix_inner_top
          shift: [16,-36.5]
          rotate: 90
