units:
  kx: cx
  ky: cy
  px: kx + 2
  py: ky + 2
  led_shift_x: 0
  led_shift_y: 4.5
  mounting_hole_radius: 2.4
  led_3dmodel_xyz_rotation_x: 0
  led_3dmodel_xyz_rotation_y: 180
  led_3dmodel_xyz_rotation_z: 0
  led_3dmodel_xyz_offset_x: 0
  led_3dmodel_xyz_offset_y: 5.1
  led_3dmodel_xyz_offset_z: -1.7
points:
  key:
    padding: cy+0.1
    spread: cx+0.1
  zones:
    matrix:
      anchor:
        rotate: 0
        shift: [75, -75]
      columns:
        macro:
          key:
            tag: choc1u
            column_net: C1
        pinky:
          key:
            tag: choc1u
            column_net: C2
        ring:
          key:
            splay: 0
            origin: [-12, -19]
            stagger: 5
            tag: choc1u
            column_net: C3
        middle:
          key:
            stagger: 3
            tag: choc1u
            column_net: C4
        index:
          key:
            stagger: -3
            tag: choc1u
            column_net: C5
        inner:
          key:
            stagger: -3
            tag: choc1u
            column_net: C6
      rows:
        bottom:
          row_net: R3
        middle:
          row_net: R2
        top:
          row_net: R1
        # num:
        #   row_net: P104
    thumbfan:
      anchor:
        ref: matrix_index_bottom
        shift: [-12, -17.5]
      columns:
        near:
          key:
            splay: 0
            tag: choc1u
            column_net: C4
        home:
          key:
            spread: 21.25
            splay: -15
            stagger: -3
            tag: choc1u
            column_net: C5
        far:
          key:
            spread: 23.25
            splay: -20
            stagger: -0
            tag: choc15u
            rotate: 90
            column_net: C6
      rows:
        thumb:
          row_net: R4
          
  rotate: 0
  # mirror:
  #   ref: thumbfan_far_thumb
  #   distance: 100
outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5,ky-0.5]
    - what: rectangle
      where: thumbfan_far_thumb
      size: [kx-0.5,1.5ky-0.5]

  key_cutout:
    - what: rectangle
      where: true
      size: [14, 14]
  
  # mounting_holes:
  #   - what: circle
  #     where: matrix_macro_top
  #     radius: mounting_hole_radius
  #     adjust:
  #       shift: [0.5cx,3]
  #   - what: circle
  #     where: matrix_ring_middle
  #     radius: mounting_hole_radius
  #     adjust:
  #       shift: [0.5cx,5]
  #   - what: circle
  #     where: matrix_index_top
  #     radius: mounting_hole_radius
  #     adjust:
  #       shift: [0.5cx,3]
  #   - what: circle
  #     where: matrix_macro_bottom
  #     radius: mounting_hole_radius
  #     adjust:
  #       shift: [0.5cx,3]
  #   - what: circle
  #     where: matrix_index_bottom
  #     radius: mounting_hole_radius
  #     adjust:
  #       shift: [0.5cx,3]
  #   - what: circle
  #     where: matrix_middle_bottom
  #     radius: mounting_hole_radius
  #     adjust:
  #       shift: [-0.5cx+3,-0.5cy-5]
  #   - what: circle
  #     where: thumbfan_far_thumb
  #     radius: mounting_hole_radius
  #     adjust:
  #       shift: [0.5cx-4,0.5cy+3]

  board:
    - what: polygon
      operation: stack
      fillet: 1.5
      points:
        # Top left
        - ref: matrix_macro_top
          shift: [-0.5px-1,0.5py+5]
        # Bottom left
        - ref: matrix_macro_bottom
          shift: [-0.5px-1,-0.5py]
        # Notch under Ring col
        - ref: matrix_ring_bottom
          shift: [-7,-0.5py-5]
        - ref: matrix_ring_bottom
          shift: [0.5px-8,-0.5py-5]
        # Around thumbfan
        - ref: thumbfan_near_thumb
          shift: [-0.5px+0.5,-0.5px+0.5]
        - ref: thumbfan_home_thumb
          shift: [0.5px-0.5,-0.5py-1.5]
        - ref: thumbfan_far_thumb
          shift: [-0.5px-5,-0.5py] #Remember, it's rotated!
        - ref: matrix_inner_bottom
          shift: [0.5px+22,-0.5py-4]
        - ref: matrix_inner_bottom # Start of cable notch
          shift: [0.5px+22,-5]
        - ref: matrix_inner_bottom
          shift: [0.5px+20.4,-5]
        - ref: matrix_inner_bottom
          shift: [0.5px+18.8,-5]
        - ref: matrix_inner_bottom
          shift: [0.5px+18.8,-1]
        - ref: matrix_inner_bottom
          shift: [0.5px+22,-1] # End of cable notch
        # Top right above MCU
        - ref: matrix_inner_top
          shift: [1.5px+2,0.5py-4]
        # Step above MCU
        - ref: matrix_inner_top
          shift: [0.5px,0.5py-4.001]
        - ref: matrix_inner_top
          shift: [0.5px,0.5py]
        - ref: matrix_inner_top
          shift: [-0.5px+2,0.5py]
        - ref: matrix_inner_top
          shift: [-0.5px+2,0.5py+3.001]
        # - ref: matrix_index_top
        #   shift: [-0.5px+2,0.5py]
        - ref: matrix_middle_top
          shift: [0.5px,0.5py-3]
        - ref: matrix_middle_top
          shift: [0.5px,0.5py+0.501]
        - ref: matrix_middle_top
          shift: [-0.5px,0.5py+0.501]
        - ref: matrix_middle_top
          shift: [-0.5px,0.5py-3]
    # - operation: subtract
    #   name: mounting_holes

  combo:
    - name: board
    - operation: subtract
      name: keys

pcbs:
  main_pcb:
    template: kicad8 # Required, since footprints are KiCad 8 only
    outlines:
      main:
        outline: board
    footprints:
      choc_hotswap_15:
        what: garethbradley/choc
        where: thumbfan_far_thumb
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
          show_keycaps: false
          reverse: true
          hotswap: true
          keycap_3dmodel_filename: ${EG_GARETHBRADLEY_3D_MODELS}/MBK_Keycap_-_1.5u.step
          # keycap_3dmodel_xyz_rotation: [0, 0, 90]
          keycap_3dmodel_xyz_offset: [-27, 0, 6.5]
      
      choc_hotswap:
        what: garethbradley/choc
        where: -thumbfan_far_thumb
        adjust:
          rotate: 180
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
          # keycaps: true
          reverse: true
          hotswap: true
          keycap_3dmodel_filename: ${EG_INFUSED_KIM_3D_MODELS}/Choc_V1_Keycap_MBK_Black_1u.step
      
      # TOP ROW
      rgb_1:
        what: ceoloide/led_sk6812mini-e
        where: matrix_inner_top
        params:
          reversible: true
          led_3dmodel_filename: '${EG_GARETHBRADLEY_3D_MODELS}/LED_SK6812MINI-E.step'
          led_3dmodel_xyz_rotation: [0, 180, 0]
          led_3dmodel_xyz_offset: [0, 5.1, -1.7]
          P4: RGB
          P2: RGB_2
          P1: RAW
          P3: LED_DRAIN
        adjust:
          shift: [led_shift_x, led_shift_y]
          rotate: 180

      rgb_2:
        what: ceoloide/led_sk6812mini-e
        where: matrix_index_top
        params:
          reversible: true
          led_3dmodel_filename: '${EG_GARETHBRADLEY_3D_MODELS}/LED_SK6812MINI-E.step'
          led_3dmodel_xyz_rotation: [0, 180, 0]
          led_3dmodel_xyz_offset: [0, 5.1, -1.7]
          P4: RGB_2
          P2: RGB_3
          P1: RAW
          P3: LED_DRAIN
        adjust:
          shift: [led_shift_x, led_shift_y]
          rotate: 180

      rgb_3:
        what: ceoloide/led_sk6812mini-e
        where: matrix_middle_top
        params:
          reversible: true
          led_3dmodel_filename: '${EG_GARETHBRADLEY_3D_MODELS}/LED_SK6812MINI-E.step'
          led_3dmodel_xyz_rotation: [0, 180, 0]
          led_3dmodel_xyz_offset: [0, 5.1, -1.7]
          P4: RGB_3
          P2: RGB_4
          P1: RAW
          P3: LED_DRAIN
        adjust:
          shift: [led_shift_x, led_shift_y]
          rotate: 180

      rgb_4:
        what: ceoloide/led_sk6812mini-e
        where: matrix_ring_top
        params:
          reversible: true
          led_3dmodel_filename: '${EG_GARETHBRADLEY_3D_MODELS}/LED_SK6812MINI-E.step'
          led_3dmodel_xyz_rotation: [0, 180, 0]
          led_3dmodel_xyz_offset: [0, 5.1, -1.7]
          P4: RGB_4
          P2: RGB_5
          P1: RAW
          P3: LED_DRAIN
        adjust:
          shift: [led_shift_x, led_shift_y]
          rotate: 180

      rgb_5:
        what: ceoloide/led_sk6812mini-e
        where: matrix_pinky_top
        params:
          reversible: true
          led_3dmodel_filename: '${EG_GARETHBRADLEY_3D_MODELS}/LED_SK6812MINI-E.step'
          led_3dmodel_xyz_rotation: [0, 180, 0]
          led_3dmodel_xyz_offset: [0, 5.1, -1.7]
          P4: RGB_5
          P2: RGB_6
          P1: RAW
          P3: LED_DRAIN
        adjust:
          shift: [led_shift_x, led_shift_y]
          rotate: 180

      rgb_6:
        what: ceoloide/led_sk6812mini-e
        where: matrix_macro_top
        params:
          reversible: true
          led_3dmodel_filename: '${EG_GARETHBRADLEY_3D_MODELS}/LED_SK6812MINI-E.step'
          led_3dmodel_xyz_rotation: [0, 180, 0]
          led_3dmodel_xyz_offset: [0, 5.1, -1.7]
          P4: RGB_6
          P2: RGB_7
          P1: RAW
          P3: LED_DRAIN
        adjust:
          shift: [led_shift_x, led_shift_y]
          rotate: 180

      # MIDDLE ROW
      rgb_7:
        what: ceoloide/led_sk6812mini-e
        where: matrix_macro_middle
        params:
          reversible: true
          led_3dmodel_filename: '${EG_GARETHBRADLEY_3D_MODELS}/LED_SK6812MINI-E.step'
          led_3dmodel_xyz_rotation: [0, 180, 0]
          led_3dmodel_xyz_offset: [0, 5.1, -1.7]
          P4: RGB_7
          P2: RGB_8
          P1: RAW
          P3: LED_DRAIN
        adjust:
          shift: [led_shift_x, led_shift_y]
          rotate: 0

      rgb_8:
        what: ceoloide/led_sk6812mini-e
        where: matrix_pinky_middle
        params:
          reversible: true
          led_3dmodel_filename: '${EG_GARETHBRADLEY_3D_MODELS}/LED_SK6812MINI-E.step'
          led_3dmodel_xyz_rotation: [0, 180, 0]
          led_3dmodel_xyz_offset: [0, 5.1, -1.7]
          P4: RGB_8
          P2: RGB_9
          P1: RAW
          P3: LED_DRAIN
        adjust:
          shift: [led_shift_x, led_shift_y]
          rotate: 0

      rgb_9:
        what: ceoloide/led_sk6812mini-e
        where: matrix_ring_middle
        params:
          reversible: true
          led_3dmodel_filename: '${EG_GARETHBRADLEY_3D_MODELS}/LED_SK6812MINI-E.step'
          led_3dmodel_xyz_rotation: [0, 180, 0]
          led_3dmodel_xyz_offset: [0, 5.1, -1.7]
          P4: RGB_9
          P2: RGB_10
          P1: RAW
          P3: LED_DRAIN
        adjust:
          shift: [led_shift_x, led_shift_y]
          rotate: 0

      rgb_10:
        what: ceoloide/led_sk6812mini-e
        where: matrix_middle_middle
        params:
          reversible: true
          led_3dmodel_filename: '${EG_GARETHBRADLEY_3D_MODELS}/LED_SK6812MINI-E.step'
          led_3dmodel_xyz_rotation: [0, 180, 0]
          led_3dmodel_xyz_offset: [0, 5.1, -1.7]
          P4: RGB_10
          P2: RGB_11
          P1: RAW
          P3: LED_DRAIN
        adjust:
          shift: [led_shift_x, led_shift_y]
          rotate: 0

      rgb_11:
        what: ceoloide/led_sk6812mini-e
        where: matrix_index_middle
        params:
          reversible: true
          led_3dmodel_filename: '${EG_GARETHBRADLEY_3D_MODELS}/LED_SK6812MINI-E.step'
          led_3dmodel_xyz_rotation: [0, 180, 0]
          led_3dmodel_xyz_offset: [0, 5.1, -1.7]
          P4: RGB_11
          P2: RGB_12
          P1: RAW
          P3: LED_DRAIN
        adjust:
          shift: [led_shift_x, led_shift_y]
          rotate: 0

      rgb_12:
        what: ceoloide/led_sk6812mini-e
        where: matrix_inner_middle
        params:
          reversible: true
          led_3dmodel_filename: '${EG_GARETHBRADLEY_3D_MODELS}/LED_SK6812MINI-E.step'
          led_3dmodel_xyz_rotation: [0, 180, 0]
          led_3dmodel_xyz_offset: [0, 5.1, -1.7]
          P4: RGB_12
          P2: RGB_13
          P1: RAW
          P3: LED_DRAIN
        adjust:
          shift: [led_shift_x, led_shift_y]
          rotate: 0

      # BOTTOM ROW
      rgb_13:
        what: ceoloide/led_sk6812mini-e
        where: matrix_inner_bottom
        params:
          reversible: true
          led_3dmodel_filename: '${EG_GARETHBRADLEY_3D_MODELS}/LED_SK6812MINI-E.step'
          led_3dmodel_xyz_rotation: [0, 180, 0]
          led_3dmodel_xyz_offset: [0, 5.1, -1.7]
          P4: RGB_13
          P2: RGB_14
          P1: RAW
          P3: LED_DRAIN
        adjust:
          shift: [led_shift_x, led_shift_y]
          rotate: 180

      rgb_14:
        what: ceoloide/led_sk6812mini-e
        where: matrix_index_bottom
        params:
          reversible: true
          led_3dmodel_filename: '${EG_GARETHBRADLEY_3D_MODELS}/LED_SK6812MINI-E.step'
          led_3dmodel_xyz_rotation: [0, 180, 0]
          led_3dmodel_xyz_offset: [0, 5.1, -1.7]
          P4: RGB_14
          P2: RGB_15
          P1: RAW
          P3: LED_DRAIN
        adjust:
          shift: [led_shift_x, led_shift_y]
          rotate: 180

      rgb_15:
        what: ceoloide/led_sk6812mini-e
        where: matrix_middle_bottom
        params:
          reversible: true
          led_3dmodel_filename: '${EG_GARETHBRADLEY_3D_MODELS}/LED_SK6812MINI-E.step'
          led_3dmodel_xyz_rotation: [0, 180, 0]
          led_3dmodel_xyz_offset: [0, 5.1, -1.7]
          P4: RGB_15
          P2: RGB_16
          P1: RAW
          P3: LED_DRAIN
        adjust:
          shift: [led_shift_x, led_shift_y]
          rotate: 180

      rgb_16:
        what: ceoloide/led_sk6812mini-e
        where: matrix_ring_bottom
        params:
          reversible: true
          led_3dmodel_filename: '${EG_GARETHBRADLEY_3D_MODELS}/LED_SK6812MINI-E.step'
          led_3dmodel_xyz_rotation: [0, 180, 0]
          led_3dmodel_xyz_offset: [0, 5.1, -1.7]
          P4: RGB_16
          P2: RGB_17
          P1: RAW
          P3: LED_DRAIN
        adjust:
          shift: [led_shift_x, led_shift_y]
          rotate: 180

      rgb_17:
        what: ceoloide/led_sk6812mini-e
        where: matrix_pinky_bottom
        params:
          reversible: true
          led_3dmodel_filename: '${EG_GARETHBRADLEY_3D_MODELS}/LED_SK6812MINI-E.step'
          led_3dmodel_xyz_rotation: [0, 180, 0]
          led_3dmodel_xyz_offset: [0, 5.1, -1.7]
          P4: RGB_17
          P2: RGB_18
          P1: RAW
          P3: LED_DRAIN
        adjust:
          shift: [led_shift_x, led_shift_y]
          rotate: 180

      rgb_18:
        what: ceoloide/led_sk6812mini-e
        where: matrix_macro_bottom
        params:
          reversible: true
          led_3dmodel_filename: '${EG_GARETHBRADLEY_3D_MODELS}/LED_SK6812MINI-E.step'
          led_3dmodel_xyz_rotation: [0, 180, 0]
          led_3dmodel_xyz_offset: [0, 5.1, -1.7]
          P4: RGB_18
          P2: RGB_19
          P1: RAW
          P3: LED_DRAIN
        adjust:
          shift: [led_shift_x, led_shift_y]
          rotate: 180

      # THUMBFAN ROW
      rgb_19:
        what: ceoloide/led_sk6812mini-e
        where: thumbfan_near_thumb
        params:
          reversible: true
          led_3dmodel_filename: '${EG_GARETHBRADLEY_3D_MODELS}/LED_SK6812MINI-E.step'
          led_3dmodel_xyz_rotation: [0, 180, 0]
          led_3dmodel_xyz_offset: [0, 5.1, -1.7]
          P4: RGB_19
          P2: RGB_20
          P1: RAW
          P3: LED_DRAIN
        adjust:
          shift: [led_shift_x, led_shift_y]
          rotate: 0

      rgb_20:
        what: ceoloide/led_sk6812mini-e
        where: thumbfan_home_thumb
        params:
          reversible: true
          led_3dmodel_filename: '${EG_GARETHBRADLEY_3D_MODELS}/LED_SK6812MINI-E.step'
          led_3dmodel_xyz_rotation: [0, 180, 0]
          led_3dmodel_xyz_offset: [0, 5.1, -1.7]
          P4: RGB_20
          P2: RGB_21
          P1: RAW
          P3: LED_DRAIN
        adjust:
          shift: [led_shift_x, led_shift_y]
          rotate: 0

      rgb_21:
        what: ceoloide/led_sk6812mini-e
        where: thumbfan_far_thumb
        params:
          reversible: true
          led_3dmodel_filename: '${EG_GARETHBRADLEY_3D_MODELS}/LED_SK6812MINI-E.step'
          led_3dmodel_xyz_rotation: [0, 180, 0]
          led_3dmodel_xyz_offset: [0, 5.1, -1.7]
          P4: RGB_21
          P2: RGB_22
          P1: RAW
          P3: LED_DRAIN
        adjust:
          shift: [-led_shift_x, -led_shift_y]
          rotate: 0
      
      diode:
        what: infused-kim/diode
        where: -thumbfan_far_thumb
        params:
          include_tht: false
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [7, 3.5]
          rotate: 270

      diode_thumbfan_far:
        what: infused-kim/diode
        where: thumbfan_far_thumb
        params:
          include_tht: false
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [-7, -3.5]
          rotate: 90
      # led:
      #   what: ceoloide/led_sk6812mini-e
      #   where: true
      #   params:
      #     P2:
      #   adjust:
      #     shift: [0, -8]
      nice_nano:
        what: garethbradley/mcu_nice_nano_v2
        params:
          show_via_labels: false
          # reversible: true
          # reverse_mount: true
          mcu_3dmodel_filename: ${EG_INFUSED_KIM_3D_MODELS}/Nice_Nano_V2.step
          P006: CS
          P017: MOSI
          P020: SCK
          P008: RGB
          
          P022: NC1
          P024: NC2
          P100: VRGB
          P011: VLCD
          P104: R1
          P106: R2

          P009: R3
          P010: R4
          P111: C6
          P113: C5
          P115: C4
          P002: C3
          P029: C2
          P031: C1
        where:
          ref: matrix_inner_top
          shift: [px+1,-11.5]
          rotate: 0
      nice_view:
        what: garethbradley/nice_view_reversible
        params:
          show_labels: false
          jumpers_at_bottom: false
          reverse: true
          VCC: VLCD
          # reverse_mount: true
        where:
          ref: matrix_inner_top
          shift: [px+1,-14.5]
          rotate: 0
      batt_conn:
        what: garethbradley/battery_connector_jst_ph_2_smd
        where:
          ref: matrix_inner_top
          shift: [21.5,-37]
          rotate: 90
        params:
          reversible: true
      mosfet_rgb:
        what: garethbradley/mosfet_pjc7400
        where:
          ref: matrix_inner_top
          shift: [23,-46.5]
          rotate: 180
        params:
          reversible: true
          mosfet_3dmodel_filename: ${EG_GARETHBRADLEY_3D_MODELS}/SOT323.step
          source: GND
          drain: LED_DRAIN
          gate: VRGB
      switch_power:
        what: ceoloide/power_switch_smd_side
        where:
          ref: matrix_macro_top
          shift: [0,0.5py+3.3]
          rotate: 90
        params:
          side: 'B'
          reversible: true
          switch_3dmodel_filename: ${EG_INFUSED_KIM_3D_MODELS}/Switch_Power.step
          switch_3dmodel_xyz_offset: [0, 0, 0]
          switch_3dmodel_xyz_rotation: [90, 180, 90]
          switch_3dmodel_xyz_scale: [1, 1, 1]
      switch_reset_1:
        what: infused-kim/switch_reset
        where:
          ref: matrix_pinky_top
          shift: [0,0.5py+3.4]
          rotate: 90
        params:
          side: 'B'
          reverse: true
      # mounting_hole_1:
      #   what: ceoloide/mounting_hole_plated
      #   where:
      #     ref: matrix_macro_top
      #     shift: [0.5cx,-0.5cy]
      # mounting_hole_2:
      #   what: ceoloide/mounting_hole_plated
      #   where:
      #     ref: matrix_macro_middle
      #     shift: [0.5cx,-0.5cy]
      # mounting_hole_3:
      #   what: ceoloide/mounting_hole_plated
      #   where:
      #     ref: matrix_index_top
      #     shift: [0.5cx,-0.5cy-1]
